#include "stdafx.h"
#include <moneta/pp/sql_entity.hxx>

MONETA_DEFINE_AND_DESCRIBE_ENTITY_WITH_NAMESPACE(
	(moneta)(model), big_entity_0,
	((int, unknown_1))
	((int, unknown_2))
	((int, unknown_3))
	((int, unknown_4))
	((int, unknown_5))
	((int, unknown_6))
	((int, unknown_7))
	((int, unknown_8))
	((int, unknown_9))
	((int, unknown_10))
	((int, unknown_11))
	((int, unknown_12))
	((int, unknown_13))
	((int, unknown_14))
	((int, unknown_15))
	((int, unknown_16))
	((int, unknown_17))
	((int, unknown_18))
	((int, unknown_19))
	((int, unknown_20))
	((int, unknown_21))
	((int, unknown_22))
	((int, unknown_23))
	((int, unknown_24))
	((int, unknown_25))
	((int, unknown_26))
	((int, unknown_27))
	((int, unknown_28))
	((int, unknown_29))
	((int, unknown_30))
	((int, unknown_31))
	((int, unknown_32))
	((int, unknown_33))
	((int, unknown_34))
	((int, unknown_35))
	((int, unknown_36))
	((int, unknown_37))
	((int, unknown_38))
	((int, unknown_39))
	((int, unknown_40))
	((int, unknown_41))
	((int, unknown_42))
	((int, unknown_43))
	((int, unknown_44))
	((int, unknown_45))
	((int, unknown_46))
	((int, unknown_47))
	((int, unknown_48))
	((int, unknown_49))
	((int, unknown_50))
)

BOOST_AUTO_TEST_CASE(big_entity_test) {
	moneta::model::big_entity_0 a;
	a.unknown_1 = 1;
}
