#define CLASS_NAME      MONETA_PP_ENTITY_NAME(ENTITY_DEFINITION)
#define CLASS_NAMESPACE MONETA_PP_ENTITY_NAMESPACE(ENTITY_DEFINITION)

#define CLASS_MEMBERLEVEL_MIX  PP_KVS_PATH_VALUE(ENTITY_DEFINITION, (ENTITY_MEMBERS)(ENTITY_MEMBER))
#define CLASS_MEMBER_DATATYPES  PP_KVS_VALUES(CLASS_MEMBERLEVEL_MIX, MEMBER_DATATYPE)
#define CLASS_MEMBER_NAMES      PP_KVS_VALUES(CLASS_MEMBERLEVEL_MIX, MEMBER_NAME)
